# Generated by Django 4.2.1 on 2023-06-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('employee_name', models.CharField(db_column='Employee_Name', max_length=100)),
                ('empid', models.BigIntegerField(db_column='EmpID', primary_key=True, serialize=False)),
                ('marriedid', models.BigIntegerField(db_column='MarriedID')),
                ('genderid', models.BigIntegerField(db_column='GenderID')),
                ('empstatusid', models.BigIntegerField(db_column='EmpStatusID')),
                ('deptid', models.BigIntegerField(db_column='DeptID')),
                ('fromdiversityjobfairid', models.BigIntegerField(db_column='FromDiversityJobFairID')),
                ('salary', models.BigIntegerField(db_column='Salary')),
                ('termd', models.BigIntegerField(db_column='Termd')),
                ('positionid', models.BigIntegerField(db_column='PositionID')),
                ('position', models.CharField(db_column='Position', max_length=100)),
                ('state', models.CharField(db_column='State', max_length=10)),
                ('sex', models.CharField(db_column='Sex', max_length=10)),
                ('maritaldesc', models.CharField(db_column='MaritalDesc', max_length=50)),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
    ]
